"""changed submission relationship

Revision ID: 4436a97fa2fb
Revises: f6dd2ebf78d8
Create Date: 2024-11-12 13:44:58.630479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4436a97fa2fb'
down_revision = 'f6dd2ebf78d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_enrollment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_submissions_student_id_students', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_course_enrollment_id_course_enrollments'), 'course_enrollments', ['course_enrollment_id'], ['id'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_submissions_course_enrollment_id_course_enrollments'), type_='foreignkey')
        batch_op.create_foreign_key('fk_submissions_student_id_students', 'students', ['student_id'], ['id'])
        batch_op.drop_column('course_enrollment_id')

    # ### end Alembic commands ###
