"""added description

Revision ID: 487bdce8bd03
Revises: 4436a97fa2fb
Create Date: 2024-11-22 21:45:10.496014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487bdce8bd03'
down_revision = '4436a97fa2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
