"""new attributes

Revision ID: 98fc073c9ab6
Revises: d9bfd4fb4a2a
Create Date: 2024-11-08 00:06:11.828273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fc073c9ab6'
down_revision = 'd9bfd4fb4a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Integer(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('gpa')
        batch_op.drop_column('major')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('credits')

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
