"""changed submission text

Revision ID: aab9c3fc2162
Revises: c24871d1ed32
Create Date: 2024-11-26 23:47:18.352440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab9c3fc2162'
down_revision = 'c24871d1ed32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_text', sa.String(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('submission_text')

    # ### end Alembic commands ###
