"""added approved to enrollment


Revision ID: c24871d1ed32
Revises: 3f8b2cc838ed
Create Date: 2024-11-26 17:28:36.069681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24871d1ed32'
down_revision = '3f8b2cc838ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
